name: Generate Resume HTML

on:
  push:
    branches: [main, master]
  workflow_dispatch:

# Needed to push changes back to the repository
permissions:
  contents: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install resume-md
        run: |
          python -m pip install --upgrade pip
          pip install resume-md
      
      - name: Generate Resume HTML
        run: |
          # Generate HTML from Markdown
          resume-md --input resume.md --output index.html
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html
          git commit -m "Auto-generate resume HTML" || echo "No changes to commit"
          git push 